### ISSUE TITLE
Option clipboard=unnamed ignored on Neovim

### ISSUE THREAD

**Issue by gustavo-hms** [svermeulen/vim-easyclip#55] opened 2015-04-22 12:13 UTC
I have both Vim and Neovim configured with “set clipboard=unnamed”. It works as expected for both Vim and Neovim: if I yank something on (Neo)Vim, it is placed in the * register; also, if I copy something on another program, again the * register is updated. When I paste something without specifying a register, the content of the * register is used.

Nevertheless, if I enable the Easyclip plugin on Neovim, the “clipboard=unnamed” option starts to be ignored completely. All unnamed operations start to use the " register, not the * one. Vim remains working though.

I'm not sure if this problem should be issued here or on Neovim repository. But the oddity is that it's only happening when Easyclip is enabled on Neovim.

**Comment by svermeulen** [comment] 2015-04-22 13:21
Guess I'll have to finally give neovim a go to see what's going on there.   I use "clipboard=unnamed" as well.  Thanks for the report.

**Comment by gustavo-hms** [comment] 2015-04-24 12:06
Great! Thanks
If you need more info, don't hesitate to ask

**Comment by lazywei** [comment] 2015-04-28 16:41
will it work with `clipboard=unnamedplus`?

**Comment by gustavo-hms** [comment] 2015-04-28 16:48
No, it doesn't. Same behaviour as before.

**Comment by alcesleo** [comment] 2015-08-08 10:30
Does anyone have an idea about this? I miss easyclip in my setup!

**Comment by svermeulen** [comment] 2015-08-08 20:49
I work primarily on windows so I can't debug this issue yet.  `clipboard=unnamed` doesn't even work yet on windows in neovim so I am blocked (details [here](https://www.reddit.com/r/neovim/comments/3g94le/how_to_set_up_clipboard_provider_on_windows_for/))  If somebody else wants to take a look in the meantime, I accept pull requests :)

**Comment by alcesleo** [comment] 2015-08-08 22:25
Ah, okay. I'd love to fix it but I have a lot to learn about vim plugins
just to get started. I might take a look if I have time someday - any clues
to where in the code the problem might lie?

**Comment by simonweil** [comment] 2015-08-09 08:32
Can this issue be related to: neovim/neovim#3141?

**Comment by alcesleo** [comment] 2015-08-09 08:37
Could be, they might have made the setting backwards incompatible in some
way, hopefully it will just start working if they fix that

**Comment by svermeulen** [comment] 2015-08-09 19:26
I took a brief look at this on a ubuntu virtualbox, and it looks like easyclip is doing things correctly with `clipboard=unnamed`.  It seems very likely that it's related to neovim/neovim#3141

**Comment by simonweil** [comment] 2015-08-10 05:48
neovim/neovim#3141 has been merged.
Does this issue still exist with neovim head?

**Comment by gustavo-hms** [comment] 2015-08-10 12:13
I’ve just updated my neovim installation and it seems to be working now. I thing this issue can be closed.

**Comment by alcesleo** [comment] 2015-08-10 12:31
I can confirm, awesome!

**Closed** 2015-08-10 14:23 UTC
